### ISSUE TITLE
Provide version as commit id when clio is built from repo

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/clio#34]
**Steps to reproduce the problem:**

1. Build `clio` from this repo.
2. Launch clio (or `clio --version`)
Notice that the version is shown as `clio version dev`

```
clio
> Checking authentication...
> Starting clio (version dev)...
```

**Expected Behavior:**
Provide version as commit id(similar to gptscript).

**Comment by drpebcak** [comment]
This has been completed. If you do a build from main now you will get a hash in your version.
